//go:build !ignore_autogenerated

/*
Copyright 2024 EasyStack, Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/NVIDIA/mig-parted/pkg/types"
	configv1 "github.com/easystack/accelerator-manager/api/config/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSyncStatus) DeepCopyInto(out *ConfigSyncStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSyncStatus.
func (in *ConfigSyncStatus) DeepCopy() *ConfigSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultModeStatus) DeepCopyInto(out *DefaultModeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultModeStatus.
func (in *DefaultModeStatus) DeepCopy() *DefaultModeStatus {
	if in == nil {
		return nil
	}
	out := new(DefaultModeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	if in.VnpuStatuses != nil {
		in, out := &in.VnpuStatuses, &out.VnpuStatuses
		*out = make([]VnpuStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericModeStatus) DeepCopyInto(out *GenericModeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericModeStatus.
func (in *GenericModeStatus) DeepCopy() *GenericModeStatus {
	if in == nil {
		return nil
	}
	out := new(GenericModeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicy) DeepCopyInto(out *GpuNodePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicy.
func (in *GpuNodePolicy) DeepCopy() *GpuNodePolicy {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuNodePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicyList) DeepCopyInto(out *GpuNodePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuNodePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicyList.
func (in *GpuNodePolicyList) DeepCopy() *GpuNodePolicyList {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuNodePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicySpec) DeepCopyInto(out *GpuNodePolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VcudaConfig != nil {
		in, out := &in.VcudaConfig, &out.VcudaConfig
		*out = new(VcudaConfigSpec)
		**out = **in
	}
	if in.TimeSlicingConfig != nil {
		in, out := &in.TimeSlicingConfig, &out.TimeSlicingConfig
		*out = new(TimeSlicingConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MigConfig != nil {
		in, out := &in.MigConfig, &out.MigConfig
		*out = new(MigConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicySpec.
func (in *GpuNodePolicySpec) DeepCopy() *GpuNodePolicySpec {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodePolicyStatus) DeepCopyInto(out *GpuNodePolicyStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]GpuNodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodePolicyStatus.
func (in *GpuNodePolicyStatus) DeepCopy() *GpuNodePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GpuNodePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodeStatus) DeepCopyInto(out *GpuNodeStatus) {
	*out = *in
	if in.TimeSlicingMode != nil {
		in, out := &in.TimeSlicingMode, &out.TimeSlicingMode
		*out = new(TimeSlicingModeStatus)
		**out = **in
	}
	if in.MigMode != nil {
		in, out := &in.MigMode, &out.MigMode
		*out = new(MigModeStatus)
		**out = **in
	}
	if in.DefaultMode != nil {
		in, out := &in.DefaultMode, &out.DefaultMode
		*out = new(DefaultModeStatus)
		**out = **in
	}
	if in.PassThroughMode != nil {
		in, out := &in.PassThroughMode, &out.PassThroughMode
		*out = new(GenericModeStatus)
		**out = **in
	}
	if in.VcudaMode != nil {
		in, out := &in.VcudaMode, &out.VcudaMode
		*out = new(GenericModeStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodeStatus.
func (in *GpuNodeStatus) DeepCopy() *GpuNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GpuNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuSelector) DeepCopyInto(out *GpuSelector) {
	*out = *in
	if in.RootDevices != nil {
		in, out := &in.RootDevices, &out.RootDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuSelector.
func (in *GpuSelector) DeepCopy() *GpuSelector {
	if in == nil {
		return nil
	}
	out := new(GpuSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigConfigSpec) DeepCopyInto(out *MigConfigSpec) {
	*out = *in
	if in.ConfigSlice != nil {
		in, out := &in.ConfigSlice, &out.ConfigSlice
		*out = make([]MigConfigSpecSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigConfigSpec.
func (in *MigConfigSpec) DeepCopy() *MigConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MigConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigConfigSpecSlice) DeepCopyInto(out *MigConfigSpecSlice) {
	*out = *in
	if in.MigDevices != nil {
		in, out := &in.MigDevices, &out.MigDevices
		*out = make(types.MigConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigConfigSpecSlice.
func (in *MigConfigSpecSlice) DeepCopy() *MigConfigSpecSlice {
	if in == nil {
		return nil
	}
	out := new(MigConfigSpecSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigModeStatus) DeepCopyInto(out *MigModeStatus) {
	*out = *in
	out.DevicePlugin = in.DevicePlugin
	out.MigParted = in.MigParted
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigModeStatus.
func (in *MigModeStatus) DeepCopy() *MigModeStatus {
	if in == nil {
		return nil
	}
	out := new(MigModeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpuNodePolicy) DeepCopyInto(out *NpuNodePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpuNodePolicy.
func (in *NpuNodePolicy) DeepCopy() *NpuNodePolicy {
	if in == nil {
		return nil
	}
	out := new(NpuNodePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NpuNodePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpuNodePolicyList) DeepCopyInto(out *NpuNodePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NpuNodePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpuNodePolicyList.
func (in *NpuNodePolicyList) DeepCopy() *NpuNodePolicyList {
	if in == nil {
		return nil
	}
	out := new(NpuNodePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NpuNodePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpuNodePolicySpec) DeepCopyInto(out *NpuNodePolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VnpuConfig != nil {
		in, out := &in.VnpuConfig, &out.VnpuConfig
		*out = new(VnpuConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpuNodePolicySpec.
func (in *NpuNodePolicySpec) DeepCopy() *NpuNodePolicySpec {
	if in == nil {
		return nil
	}
	out := new(NpuNodePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpuNodePolicyStatus) DeepCopyInto(out *NpuNodePolicyStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]NpuNodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpuNodePolicyStatus.
func (in *NpuNodePolicyStatus) DeepCopy() *NpuNodePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NpuNodePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpuNodeStatus) DeepCopyInto(out *NpuNodeStatus) {
	*out = *in
	if in.AvailableTemplates != nil {
		in, out := &in.AvailableTemplates, &out.AvailableTemplates
		*out = make(VnpuTemplates, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeviceStatuses != nil {
		in, out := &in.DeviceStatuses, &out.DeviceStatuses
		*out = make([]DeviceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpuNodeStatus.
func (in *NpuNodeStatus) DeepCopy() *NpuNodeStatus {
	if in == nil {
		return nil
	}
	out := new(NpuNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingConfigSpec) DeepCopyInto(out *TimeSlicingConfigSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]configv1.ReplicatedResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingConfigSpec.
func (in *TimeSlicingConfigSpec) DeepCopy() *TimeSlicingConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingModeStatus) DeepCopyInto(out *TimeSlicingModeStatus) {
	*out = *in
	out.DevicePlugin = in.DevicePlugin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingModeStatus.
func (in *TimeSlicingModeStatus) DeepCopy() *TimeSlicingModeStatus {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingModeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTemplate) DeepCopyInto(out *VTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTemplate.
func (in *VTemplate) DeepCopy() *VTemplate {
	if in == nil {
		return nil
	}
	out := new(VTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcudaConfigSpec) DeepCopyInto(out *VcudaConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcudaConfigSpec.
func (in *VcudaConfigSpec) DeepCopy() *VcudaConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VcudaConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in VnpuConfig) DeepCopyInto(out *VnpuConfig) {
	{
		in := &in
		*out = make(VnpuConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VnpuConfig.
func (in VnpuConfig) DeepCopy() VnpuConfig {
	if in == nil {
		return nil
	}
	out := new(VnpuConfig)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VnpuConfigSpec) DeepCopyInto(out *VnpuConfigSpec) {
	*out = *in
	if in.ConfigSlice != nil {
		in, out := &in.ConfigSlice, &out.ConfigSlice
		*out = make([]VnpuConfigSpecSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VnpuConfigSpec.
func (in *VnpuConfigSpec) DeepCopy() *VnpuConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VnpuConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VnpuConfigSpecSlice) DeepCopyInto(out *VnpuConfigSpecSlice) {
	*out = *in
	if in.DeviceFilter != nil {
		in, out := &in.DeviceFilter, &out.DeviceFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VnpuDevices != nil {
		in, out := &in.VnpuDevices, &out.VnpuDevices
		*out = make(VnpuConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VnpuConfigSpecSlice.
func (in *VnpuConfigSpecSlice) DeepCopy() *VnpuConfigSpecSlice {
	if in == nil {
		return nil
	}
	out := new(VnpuConfigSpecSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VnpuStatus) DeepCopyInto(out *VnpuStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VnpuStatus.
func (in *VnpuStatus) DeepCopy() *VnpuStatus {
	if in == nil {
		return nil
	}
	out := new(VnpuStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in VnpuTemplates) DeepCopyInto(out *VnpuTemplates) {
	{
		in := &in
		*out = make(VnpuTemplates, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VnpuTemplates.
func (in VnpuTemplates) DeepCopy() VnpuTemplates {
	if in == nil {
		return nil
	}
	out := new(VnpuTemplates)
	in.DeepCopyInto(out)
	return *out
}
