apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: accelerator-config-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: accelerator-config-manager
    app.kubernetes.io/part-of: accelerator-config-manager
  name: accelerator-config-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: accelerator-config-manager-role
subjects:
- kind: ServiceAccount
  name: accelerator-config-manager
  namespace: system
