---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ecns.easystack.io
  resources:
  - gpunodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecns.easystack.io
  resources:
  - gpunodepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - ecns.easystack.io
  resources:
  - gpunodepolicies/status
  verbs:
  - get
  - patch
  - update
